apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuitem-deployment
  labels:
    app: MenuItemListing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: MenuItemListing  
  template:
    metadata:
      labels:
        app: MenuItemListing
    spec:
      containers:
      - name: Truyumcontainer
        image: mymenuitemapi226cr.azurecr.io/mymenuitemapi226contreg226:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        imagePullSecrets:
        - name: myacrcredentails 

---
apiVersion: apps/v1
kind: Service
metadata:
   name: MenuItemListing
spec: 
   type: LoadBalancer
   ports:
   - port: 80
   selector:
    app: MenuItemListing
